spring.application.name=mustaqel_apis
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/mustaqel_java?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway owns database schema changes
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Do NOT let Hibernate modify the database schema
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true